- name: Ansible Copy Example Local to Remote
  hosts: all
  tasks:
    - name: copying file with playbook
      become: true
      copy:
        src: ~/southamerica
        dest: /
        owner: ansible
        mode: 0644

