- name: Ansible Copy Example Local to Remote
  hosts: all
  tasks:
    - name: copying file with playbook
      become: true
      copy:
        src: win_ping.yml
        dest: /home/ansible
        owner: ansible
        mode: 0644

