---
- name: Revision cambio de hora
  hosts: all
  become: yes
  tasks:
  
    - name: Revision Cambio de hora
      shell: zdump -v America/Santiago | grep 2023
      register: newhora
    - debug: var=newhora.stdout_lines
